name: Backend Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SENDGRID_API_KEY: "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"
  SENDGRID_EMAIL: "bancrotdoc@gmail.com"
  TWILIO_ACCOUNT_SID: "AC303b5fbd90d92a1af8c465b2ebfba632"
  TWILIO_AUTH_TOKEN: "8da04f9736e93821e060baddd1b5cb0d"
  TWILIO_PHONE_NUMBER: "+18317773617"
  CLIENT_URL: "http://localhost:3000"
  YOOKASSA_SHOP_ID: ${{ secrets.YOOKASSA_SHOP_ID }}
  YOOKASSA_SECRET: ${{ secrets.YOOKASSA_SECRET }}


jobs:
  migrate:
    name: Migrate Database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install deps"
        run: cd server && yarn install

      - name: "Migrate"
        run: cd server && yarn prisma migrate deploy

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./server